### ISSUE TITLE
C vulnerable programs experimentation

### ISSUE THREAD

**Issue by Jacarte** [KTH/slumps#42]
We have three sources for vulnerabilities experimentation with SLUMPs:

- Memory disclosures from #7 
- Whitebox cryptographic programs mentioned in #27 
- CVEs report for webassembly mentioned in #41 
  - TODO: Collect specific CVEs to test

**Experiment steps:**

1 - Port the vulnerable code to WebAssembly using SLUMPs and collecting the original program without optimizations
2 - See if the problem persists in the V8 context (already tested in #7 with emcc)
  - Try to execute in the browser
  - Collect the profiler information from the DevTool
  - Execute the same code in SWAM and collect stack and memory traces

3 - Feed SLUMPs with the vulnerable
4 - Collect variants
   - For each variant: apply step 2

**Notes**

*In the case of the CVEs, we also need to test if the CVEs related to Binaryen persist after the SLUMPs phase*

*Use the dockerized SLUMPs app*

**Comment by tareq97** [comment]
I am trying to run the Catalan_numbers.c example in dockerized Slump app but getting the below-mentioned output. How much time does it take in the stage LLVM BC to Souper IR candidates?
![stuck](https://user-images.githubusercontent.com/10094302/74136558-88f0bf00-4bee-11ea-96a2-e06243cbb85b.png)

**Comment by Jacarte** [comment]
It can take a while, taking into account that the souper exploration can be expensive. However, the timeout in this case (second line in your screenshot) is for half an a hour.

In the experiments that we ran the time for an answer was 2863.46 seconds.

**Comment by tareq97** [comment]
@Jacarte I am able to get into the interactive mode of slumps but after that, when I am trying to run the vulnerable program getting below mentioned error . Am i doing somethin wrong 

root@5831e19c674c:/slumps/src# python3 slumps.py interger_overflow.c
Traceback (most recent call last):
  File "slumps.py", line 5, in <module>
    from stages import CToLLStage, LLToBC, BCToSouper, ObjtoWASM, WASM2WAT, BCCountCandidates
  File "/slumps/src/stages.py", line 4, in <module>
    from utils import bcolors, Alias, config, createTmpFile, RUNTIME_CONFIG,processCandidatesMetaOutput
  File "/slumps/src/utils.py", line 17, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
root@5831e19c674c:/slumps/src# 


![entrypoint](https://user-images.githubusercontent.com/10094302/74522097-e2245f80-4f1a-11ea-9156-ff074785463d.png)

**Comment by Jacarte** [comment]
Change the python interpreter to python3.7 instead of python3, ```python3.7 slumps.py <program>```. I will fix whit in the doc

**Comment by tareq97** [comment]
using [python3.7 slumps.py integer_overflow.c] it gives a below-mentioned error. The error says No such file or directory: 'interger_overflow.c'
![vulnerable](https://user-images.githubusercontent.com/10094302/74523289-1dc02900-4f1d-11ea-8949-d5b8fb263287.png)

docker run -it --rm -v $(pwd/out:/out -v $(pwd)/vulnerable_programs/report-web-assembly-memory-safety/c --entrypoint /bin/bash jacarte/slumps:app
In the docker command i have mentioned the vulnerable code path. How should I provide the path for vulnerale program.

**Comment by Jacarte** [comment]
Should be something like this 
```
docker run -it --rm -v $(pwd):/slumps/src/out -v $(pwd)/vulnerable_programs/report-web-assembly-memory-safety/c:/slumps/src --entrypoint /bin/bash jacarte/slumps:app
```

You are missing the second part for the vulnerabilities volume, therefore, the files are not in the slumps root.

**Comment by tareq97** [comment]
Tried with the latest command. getting below error after running the slumps.py.

python3.7: can't open file 'slumps.py': [Errno 2] No such file or directory

![command](https://user-images.githubusercontent.com/10094302/74540198-a18b0d00-4f3f-11ea-80b9-da74122e7df3.png)
But the good thing is that able to see vulnerable programs list. Only thing I am not getting is how to mount the src/slumps folder so to run the slumps.py file.

**Comment by Jacarte** [comment]
Sorry my mistake, you are overriding the src folder thats why you are not seeing the scripts slumps.py. Change the second volume to ```-v $(pwd)/<vulnerable>:/input``` or other input folder name. Then you will be able to run ```python3.7 slumps.py /input/<program>.c```

**Comment by tareq97** [comment]
Thanks for the input Javier I was able to run it but ran into some issues at C to LLVR IR. Are these expected as we are running the vulnerable code?
![expectederror](https://user-images.githubusercontent.com/10094302/74550088-0d29a600-4f51-11ea-8d92-037d5e710922.png)

**Comment by Jacarte** [comment]
I see...try to remove the ```EMSCRIPTEN_KEEPALIVE``` annotation from the C code

**Comment by tareq97** [comment]
removed the EMSCRIPTEN code from the file and ran it but it is giving an error at LLVM to Souper IR stage. The error is related to redis do I need to install and configure redis db in my system.
![reddiserror](https://user-images.githubusercontent.com/10094302/74551483-8de9a180-4f53-11ea-838b-3620e314e977.png)

**Comment by Jacarte** [comment]
Changing the entrypoint for the container bypass the initialization of redis-server service. To launch it again, run ```nohup redis-server &``` in the bash console inside the container.
